# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "23ca7c868793747679555ea0ebc24006"
application_url = "https://bundle.mercsync.com"
embedded = true
name = "Bundle Stock Sync"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products,read_inventory,write_inventory,read_locations"

[webhooks]
api_version = "2025-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://bundle.mercsync.com/webhooks/privacy/customers/redact"
  customer_data_request_url = "https://bundle.mercsync.com/webhooks/privacy/customers/data_request"
  shop_deletion_url = "https://bundle.mercsync.com/webhooks/privacy/shop/redact"

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = [ "orders/paid" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory_levels/update"
  topics = [ "inventory_levels/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[auth]
redirect_urls = [
  "https://bundle.mercsync.com/auth/callback",
  "https://bundle.mercsync.com/auth/shopify/callback",
  "https://bundle.mercsync.com/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
